# This file is used for Gradle options, for the rest use stonecutter.properties.toml
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod.id=well_seasoned
mod.name=Well Seasoned
mod.group=net.syrupstudios
mod.version=0.3.0
mod.description=A breath of the wild inspired food system.
mod.authors=SodaSyrup
mod.contributors=
mod.license=RSL-1.0
mod.homepage=https://github.com/Syrup-Studios/well_seasoned
mod.issues=https://github.com/Syrup-Studios/well_seasoned/issues
mod.sources=https://github.com/Syrup-Studios/well_seasoned

publish.curseforge_project_id=1644991
publish.modrinth_project_id=3FZ72P1E
publish.release_type=beta

deps.minecraft=[VERSIONED]
deps.fabric_loader=[VERSIONED]
deps.fabric_api=[VERSIONED]
deps.neoforge_version=[VERSIONED]
