modLoader="javafml"
loaderVersion="[47,)"
license="${license}"
issueTrackerURL="${issues}"

[[mods]]
modId="${modId}"
version="${version}"
displayName="${modName}"
displayURL="${homepage}"
authors="${authors}"
description='''${modDescription}'''

[[dependencies.${modId}]]
modId="forge"
mandatory=true
versionRange="[${forge},)"
ordering="NONE"
side="BOTH"

[[dependencies.${modId}]]
modId="minecraft"
mandatory=true
versionRange="[${mc}]"
ordering="NONE"
side="BOTH"

[[dependencies.${modId}]]
modId="syrup_library"
mandatory=true
versionRange="[0.2.0,)"
ordering="NONE"
side="BOTH"
