modLoader="javafml"
loaderVersion="[1,)"
license="${license}"
issueTrackerURL="${issues}"

[[mods]]
modId="${modId}"
version="${version}"
displayName="${modName}"
displayURL="${homepage}"
authors="${authors}"
description='''${modDescription}'''

[[dependencies.${modId}]]
modId="neoforge"
type="required"
ordering="NONE"
side="BOTH"

[[dependencies.${modId}]]
modId="minecraft"
type="required"
ordering="NONE"
side="BOTH"

${mixinConfig}
